services:
  server:
    container_name: server 
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    restart: unless-stopped
    environment:
      - ISSUER_OOBI=${ISSUER_OOBI}
      - ISSUER_PRE=${ISSUER_PRE}
      - ISSUER_REGK=${ISSUER_REGK}
      - KERIA_ENDPOINT=${KERIA_ENDPOINT:-http://keria:3901}
      - KERIA_BOOT_ENDPOINT=${KERIA_BOOT_ENDPOINT:-http://keria:3903}
    ports:
      - 3000:3000
    volumes:
      - server-data:/app/data

  keria:
    image: ${KERIA_IMAGE:-weboftrust/keria}:${KERIA_IMAGE_TAG:-0.2.0-dev3}
    environment:
      - KERI_AGENT_CORS=1
      - KERI_URL=http://keria:3902
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    volumes:
      - ./config/keria.json:/keria/config/keri/cf/keria.json
    entrypoint:
      [
       'keria',
       'start',
       '--config-dir',
       '/keria/config',
       '--config-file',
       'keria',
       '--name',
       'agent',
      ]
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://keria:3902/spec.yaml']
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    ports:
      - 3901:3901
      - 3902:3902
      - 3903:3903
volumes:
  server-data:
